from typing import overload
from serial.tools.list_ports_common import ListPortInfo

def find_unique_dev_by_pidvid(pid: int, vid: int) -> ListPortInfo | None: ...
def find_unique_dev_by_serial_number(sn: str) -> ListPortInfo | None: ...

class SR830:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, readDrops: int) -> None: ...
    @overload
    def __init__(self, SN: str) -> None: ...
    @overload
    def __init__(self, readDrops: int, SN: str) -> None: ...
    def connect(self, SN: str) -> None: ...
    def _write(self, cmd: str) -> None: ...
    def _write_read(self, cmd: str) -> str:...
    def setFrequency(self, frequency: float) -> None:...
    def readFrequency(self) -> float: ...
    def setAmplitude(self, volt: float) -> None:...
    def readAmplitude(self) -> float:...
    def readPhase(self) -> float:...
    def readSensitivity(self) -> None:...
    def setSensitivity(self, index: int) -> None:...
    def readTimeConstant(self): ...
    def setTimeConstant(self, index: int) -> None:...
    def frequencyReferenceSource(self, internal: bool) -> None: ...
    def close(self) -> None: ...
